const Routes={
    path:'api',
    version:'v1',
    routes:[
        {
            groupUrl:'todo',
            groupRoutes:[
                {
                    groupUrl:'list',
                    groupRoutes:[
                        {
                            groupUrl:'test',
                            groupRoutes:[
                                {
                                    method:'GET',
                                    url:'',
                                    controller:'TodoController',
                                    action:'GetAllTodo'
                                }
                            ]
                        },
                        {
                            method:'GET',
                            url:':id',
                            controller:'TodoController',
                            action:'GetOneTodo'
                        }
                    ]
                },
                {
                    method:'POST',
                    url:'add',
                    controller:'TodoController',
                    action:'addTodo'
                },
                {
                    method:'DELETE',
                    url:'delete/:id',
                    controller:'TodoController',
                    action:'deleteTodo'
                },
                {
                    method:'PUT',
                    url:'completed/:id',
                    controller:'TodoController',
                    action:'completedTodo'
                },
                {
                    method:'PUT',
                    url:'in-complete/:id',
                    controller:'TodoController',
                    action:'incompleteTodo'
                },
                {
                    method:'PUT',
                    url:'update/:id',
                    controller:'TodoController',
                    action:'updateTodo'
                }
            ]
        },
        {
            method:'GET',
            url:'list',
            controller:'TodoController',
            action:'GetAllTodo'
        }
    ]
};

module.exports=Routes;